controllers:
    resource: ../src/Controller/
    type: attribute

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui

authentication_token:
    path: /authentication_token
    methods: ['POST']
